### ISSUE TITLE
Notes #2

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/whyarewehere#9]
## Users
 - [x] `/account` doesn't show anything for non-admins
 - [x] For users without names, `/employee/:id` displays "has not written a bio yet. Are you ? You should write your bio."
 - [x] Low priority: It would be nice for admins to be able to edit the role of an existing user
 - [x] In the future, after dozens of students have been entered into the database, `/employees` is going to be huge and difficult to navigate to find specific users because of its current design. Consider listing users in a table, perhaps with thumbnails of their pictures in the first column.

## Reports
 - [x] In `/reports`, the "reports by project name" selections are paginated, but don't display any next/previous pagination buttons, so if the report count exceeds the per-page count, some options won't be displayed
 - [x] Some weirdness is resulting from reports not being associated with projects. 'Reports by project name' lists the names of records in the `projects` table, but doesn't list the values in `reports.project_name`, which is the field you're actually using to look up reports. There's no problem if `projects.name` is always duplicated to `reports.project_name`, but it's not in my current version of the database, so this feature is broken for me. I previously recommended that the field `project_id` be added to the reports table, and I still do.
 - [x] In `/reports`, I think changing the link label "All Projects" to "All Reports" would eliminate possible confusion over whether it leads to `/reports` or `/projects`

## Funds
 - [x] `Funds.amount` should be optional, as some funds have money regularly going into and coming out of them (like CBER's general fund), with no specific, permanent value making sense.

## Formatting, Optimization, Deprecation, etc.
 - [x] Fix codesniffer errors
 - [x] Trailing semicolon should be left off when using `<?= $var ?>`
 - [x] Some private methods have `__` at the beginning of their names and others have `Pr` at the end of their names. I recommend picking one style and making it uniform. PSR-2 standards say not to prefix with underscores, and Pr is ambiguous, so I suggest we avoid any special naming for private/protected methods.
 - [x] The `$id` parameter in `UsersController::account($id)` is immediately overwritten
 - [x] In `ReportsController`, are the lines `$this->paginate;` doing anything?
 - [x] `ReportsController::__reportIndexing($reports)` appears to run a couple database queries, not do anything with the results, and not do anything else with its parameter
 - [x] `UsersTable::getUser($userId)` can be replaced with the built-in `Table::get($userId)`
 - [x] `UsersTable::getUserByName($name)` can be replaced with the built-in `Table::findByName($name)->first();`
 - [x] In `UsersTable::sendPasswordResetEmail()`, the methods `template()`, `emailFormat()`, `helpers()`, and `viewVars()` are deprecated

**Comment by ericadestoya** [comment]
Some things I just did:
- `/account` now visible to non-admins.
- User variables in `/employee/:id` are no longer assumed to exist, and text is shown if they don't.
- Admins can now change user roles in `/edit/:id`.
- "All Projects" changed to "All Reports" in `/reports/*`.
- `Funds.amount` now optional with default null.

Some things I need to decide on:
- If we do a `reports.project_id` field instead of using the project name, we'll have to save every single project with a report on it. We would never be able to delete a project. I could just index all the names of the projects. That said, associating `reports` and `projects` totally has its own benefits. I don't know which I would prefer to do yet...
- I really like the indexes with the big pictures but also you're right about it being confusing... maybe a compromise where clicking on an employee or project's thumbnail will pop open the "flash card" for that employee or project.

Something that makes no sense to me:
- I see prev & next buttons in the "by project name" reports index.
![screenshot from 2017-09-13 12-08-50](https://user-images.githubusercontent.com/12422542/30388014-6337ab02-987c-11e7-8eff-00398ba63db4.png)

**Comment by PhantomWatson** [comment]
> we'll have to save every single project with a report on it

That's what the current codebase already seems to do (e.g. adding projects via `/projects/add` and displaying them in the `<select>` list of projects in the work report form so they can be selected).

  
> We would never be able to delete a project.

Why not? `ProjectsTable::delete()` should be fine, maybe with a `Project::beforeDelete()` check to make sure there aren't any associated work reports.

  
> I see prev & next buttons

Yeah, CakePHP's default pagination front-end code does that. I made a pagination element that doesn't display any useless buttons that I've been copying and pasting between projects, but I'm going to put into the Data Center CakePHP 3 plugin. You can [steal it here](https://github.com/BallStateCBER/datacenter-plugin-cakephp3/blob/development/src/Template/Element/pagination.ctp).

**Comment by ericadestoya** [comment]
> steal it

10-4!

I guess as long as we write a validator that asks the user if they want to delete the project, _knowing that it will delete all the work reports associated with it oh my goshhh_, then we can do `project_id`. I'm pretty much done making the switch. Just need to rewrite the tests to reflect it.

**Comment by PhantomWatson** [comment]
I'd go one step further and not even allow any projects to be deleted if any work reports are associated with it. In the weird event that there's a legitimate use case for doing that, it sounds like a situation where we can fiddle with the database manually to fix whatever went wrong instead of creating the option to accidentally delete a bunch of work reports.

So yeah, I'd make the "delete project" button a `Form->postButton(..., ..., ['confirm' => 'REALLY?!')` button and add a `Form::beforeDelete()` that returns false if any work reports are associated.

For bonus points, on the `/projects` index page, you could not even show the delete button for any projects with associated work reports.

**Comment by ericadestoya** [comment]
Caaaaan do. Once I get these tests rewritten I'll add that validation as well.

**Comment by ericadestoya** [comment]
> I made a pagination element that doesn't display any useless buttons that I've been copying and pasting between projects, but I'm going to put into the Data Center CakePHP 3 plugin.

For some reason, this plugin isn't loading on WAWH. I'm also trying to just recreate issue using the pagination element directly but, for whatever reason, I can't seem to recreate this issue.

**Comment by ericadestoya** [comment]
So, in re: the users index, I have them grouped now in columns of 5 rather than columns of 3. This should be less clunky. I had wanted to leave, if possible, larger user pictures and bold text of their name & title, just to make that info more accessible.

**Comment by ericadestoya** [comment]
All PHPCS errors fixed as of 51cfcaa. Hallelujah.

**Comment by ericadestoya** [comment]
> `ReportsController::__reportIndexing($reports)` appears to run a couple database queries, not do anything with the results, and not do anything else with its parameter

Actually, `reportIndexing` sets the view vars for the Reports index as well. See, `student_id` and `supervisor_id` are stored, and if you don't send the `$reports` through the `reportIndexing` method, they'll print on the index just as their IDs. `reportIndexing` gets the names associated with those IDs so that, in the index, they're printed as names.

**Comment by ericadestoya** [comment]
According to the docs, `viewVars()`, `emailFormat()`, and `helpers()` are _not_ deprecated. `template()` is so I changed it to `setTemplate()`.

**Comment by PhantomWatson** [comment]
> For some reason, this plugin isn't loading on WAWH...  

I wouldn't bother with loading the whole plugin just for that element.
  

> I can't seem to recreate this issue

Recreate which issue?

> `ReportsController::__reportIndexing($reports)` appears to ... not do anything else with its parameter

I forgot that in PHP 5+, objects are passed by reference by default without needing the `&` operator.  😐 

> ...are _not_ deprecated.

Are too. Check out the code for [`viewVars()`](https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1320), [`emailFormat()`](https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1441), and [`helpers()`](https://github.com/cakephp/cakephp/blob/master/src/Mailer/Email.php#L1398). Your IDE might be missing a plugin that alerts you to the use of methods and properties that are marked `@deprecated`.

**Comment by ericadestoya** [comment]
> Are too.

Snarl! You saw my "I read the docs" and raised me an "I read the source code!" Time for a `@deprecated` plugin then. (In all fairness, I _did_ read the docs... which have not been updated for those three methods.)

The issue I'm having a hard time recreating is the one where the prev & next buttons don't show up for the paginator. They show up for me, even if I load the plugin and all that.

**Comment by PhantomWatson** [comment]
If we feel like being extra awesome, we could submit updates to the docs, but ![:effort:](https://i.somethingawful.com/forumsystem/emoticons/emot-effort.gif)

Methods like `Paginator->prev()` don't check to see if there's anything to link to. You have to wrap them in `if ($this->Paginator->hasPrev())` to make them only appear when it makes sense.

**Comment by ericadestoya** [comment]
*~*~*~*effort*~*~*~* I can submit updates to the docs.

**Comment by ericadestoya** [comment]
I completely misunderstood about the pagination thing, by the way. I thought the issue was that the buttons _were not_ displaying, when they should be--not that they _were_ displaying when they shouldn't be. Solved.
